-- Run this snippet in your Supabase SQL Editor to fix the Playlist creation error.
-- It only adds the missing columns to the existing table, preventing the "relation already exists" error.

ALTER TABLE public.playlists 
ADD COLUMN IF NOT EXISTS share_code TEXT,
ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS share_count BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS save_count BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS copy_count BIGINT DEFAULT 0;

-- Create broadcasts table
CREATE TABLE IF NOT EXISTS public.broadcasts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  message TEXT NOT NULL,
  sender TEXT NOT NULL,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (id)
);

-- Enable RLS
ALTER TABLE public.broadcasts ENABLE ROW LEVEL SECURITY;

-- Allow select for everyone so the app can fetch notifications
CREATE POLICY "Anyone can select active broadcasts" ON public.broadcasts
  FOR SELECT USING (active = true);

